### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by lileini** [aliyun/aliyun-log-android-sdk#19]
java.lang.IllegalStateException
Couldn't read row 1, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java:84)

**Comment by naruto-wbb** [comment]
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetLong(Native Method)
        at android.database.CursorWindow.getLong(CursorWindow.java:511)
        at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
        at org.greenrobot.greendao.AbstractDao.loadCurrent(AbstractDao.java:541)
        at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:498)
        at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:480)
        at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
        at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
        at org.greenrobot.greendao.query.Query.list(Query.java:89)
        at com.aliyun.sls.android.sdk.SLSDatabaseManager.queryRecordFromDB(SLSDatabaseManager.java:84)
        at com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java:86)
        at com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java:19)
        at com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:69)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by naruto-wbb** [comment]
has methods of resolution?

**Comment by chaolee50** [comment]
请使用新版
```
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'
```
