### ISSUE TITLE
2.1.0使用者发生java.lang.IllegalStateException

### ISSUE THREAD

**Issue by xwc010** [aliyun/aliyun-log-android-sdk#35]
1.
Fatal Exception: java.lang.IllegalStateException: Compute signature failed!
       at com.aliyun.sls.android.sdk.utils.Utils.sign(Utils.java:101)
       at com.aliyun.sls.android.sdk.core.RequestOperation.buildCachedHeaders(RequestOperation.java:253)
       at com.aliyun.sls.android.sdk.core.RequestOperation.postCachedLog(RequestOperation.java:298)
       at com.aliyun.sls.android.sdk.LOGClient.asyncPostCachedLog(LOGClient.java:137)
       at com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java:91)
       at com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java:19)
       at com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:68)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
	   
	   
	      
Caused by java.lang.IllegalArgumentException: key.length == 0
       at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
       at com.aliyun.sls.android.sdk.core.auth.HmacSHA1Signature.sign(HmacSHA1Signature.java:83)
       at com.aliyun.sls.android.sdk.core.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:49)
       at com.aliyun.sls.android.sdk.utils.Utils.sign(Utils.java:98)
       at com.aliyun.sls.android.sdk.core.RequestOperation.buildCachedHeaders(RequestOperation.java:253)
       at com.aliyun.sls.android.sdk.core.RequestOperation.postCachedLog(RequestOperation.java:298)
       at com.aliyun.sls.android.sdk.LOGClient.asyncPostCachedLog(LOGClient.java:137)
       at com.aliyun.sls.android.sdk.CacheManager.fetchDataFromDBAndPost(CacheManager.java:91)
       at com.aliyun.sls.android.sdk.CacheManager.access$100(CacheManager.java:19)
       at com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:68)
       at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by chaolee50** [comment]
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'

您试试这个
