### ISSUE TITLE
2.1.0引起java.lang.NullPointerException

### ISSUE THREAD

**Issue by xwc010** [aliyun/aliyun-log-android-sdk#36]
Fatal Exception: java.lang.NullPointerException
       at com.aliyun.sls.android.sdk.CacheManager.access$000(CacheManager.java:19)
       at com.aliyun.sls.android.sdk.CacheManager$CacheTimerTask.run(CacheManager.java:61)
       at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by chaolee50** [comment]
implementation 'com.aliyun.openservices:aliyun-log-android-sdk:2.4.1'

您试试这个
