### ISSUE TITLE
数据库报错

### ISSUE THREAD

**Issue by xayo69** [aliyun/aliyun-log-android-sdk#44]
[Built-in Screen (type:0)] fps:56.292496,dur:1012.57,max:106.67,min:14.05
2020-10-20 17:40:48.263 10270-26546/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
2020-10-20 17:40:48.263 10270-26546/? W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:352)
2020-10-20 17:40:48.263 10270-26546/? W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:322)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at com.tencent.securitysdk.a.a.c.f(ProGuard:124)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at com.tencent.securitysdk.a.a.c.d(ProGuard:104)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at com.tencent.securitysdk.a.b.b.d(ProGuard:101)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at com.tencent.securitysdk.e.a.b.d.run(ProGuard:205)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-10-20 17:40:48.264 10270-26546/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-10-20 17:40:48.265 10270-26546/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-10-20 17:40:48.314 10270-26546/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
这个报错，怎么处理？

**Comment by chaolee50** [comment]
> [Built-in Screen (type:0)] fps:56.292496,dur:1012.57,max:106.67,min:14.05
> 2020-10-20 17:40:48.263 10270-26546/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
> 2020-10-20 17:40:48.263 10270-26546/? W/System.err: at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:352)
> 2020-10-20 17:40:48.263 10270-26546/? W/System.err: at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:322)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at com.tencent.securitysdk.a.a.c.f(ProGuard:124)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at com.tencent.securitysdk.a.a.c.d(ProGuard:104)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at com.tencent.securitysdk.a.b.b.d(ProGuard:101)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at com.tencent.securitysdk.e.a.b.d.run(ProGuard:205)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 2020-10-20 17:40:48.264 10270-26546/? W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 2020-10-20 17:40:48.265 10270-26546/? W/System.err: at java.lang.Thread.run(Thread.java:764)
> 2020-10-20 17:40:48.314 10270-26546/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
> 这个报错，怎么处理？

用的是什么版本的呢？
可以加钉钉 chaolee50 ，详细看下

**Comment by xayo69** [comment]
已经更新到最新版本了。现在没问题。
