### ISSUE TITLE
程序启动报错

### ISSUE THREAD

**Issue by xayo69** [aliyun/aliyun-log-android-sdk#45]
2020-10-22 09:21:13.423 1032-1115/? E/MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
2020-10-22 09:21:13.423 1032-1115/? W/System.err: java.lang.NullPointerException: null receiver
2020-10-22 09:21:13.423 1032-1115/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-22 09:21:13.424 1032-1115/? W/System.err:     at com.mediatek.server.MtkDataShaping.openLteGateByDataShaping(MtkDataShaping.java:36)
2020-10-22 09:21:13.424 1032-1115/? W/System.err:     at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3591)
2020-10-22 09:21:13.424 1032-1115/? W/System.err:     at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:3769)

**Comment by xayo69** [comment]
LogProducerClient 这些类有没有说明文档或者api文档

**Comment by chaolee50** [comment]
错误是这个项目报出来的？

LogProducerClient 在app和README有说明，是哪方面没有理解呢？

**Comment by xayo69** [comment]
> 错误是这个项目报出来的？
> 
> LogProducerClient在app和README有说明，是哪方面没有理解呢？

已经好了，非常感谢！
