### ISSUE TITLE
so库问题

### ISSUE THREAD

**Issue by ZuJunJun** [aliyun/aliyun-log-android-sdk#69]
1、按照阿里云 日志服务SLS 使用Maven方式集成了SDK
2、在官方文档以及github仓库都没看到so资源下载或者自己编译so文件的操作
3、报错如下：    java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/com.xxx.xxx/app_libs/libsls_producer.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1632)
        at com.aliyun.sls.android.producer.utils.SoLoader.loadLibrary(SoLoader.java:55)
4、谢谢

**Comment by lejiteyu** [comment]
I get the same wrong.  java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxx.xxx/app_libs/libsls_producer.so" not found
How do you resolve this problem?

**Comment by henryhong111** [comment]
遇到了类似的问题 maven 方式集成
版本号：2.6.4

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxxx.xxx/app_libs/libsls_producer.so" not found
       at java.lang.Runtime.load0(Runtime.java:929)
       at java.lang.System.load(System.java:1625)
       at OooOO0o.OooOO0.OooOO0(SoLoader.java:6)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:7)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:4)
