### ISSUE TITLE
LogProducerConfig初始化时出现崩溃

### ISSUE THREAD

**Issue by HelloFish-2016** [aliyun/aliyun-log-android-sdk#83]
在初始化LogProducerConfig的时候，报了这个错误，使用版本如下：
com.aliyun.openservices:aliyun-log-android-sdk:2.6.2
错误堆栈如下：
java.lang.UnsatisfiedLinkError: 
No implementation found for void com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_source(long, java.lang.String) (tried Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1source and Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1source__JLjava_lang_String_2)
com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_source(Native Method)
com.aliyun.sls.android.producer.LogProducerConfig.setSource(LogProducerConfig.java:306)
com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:53)
com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:36)
com.mango.base.work.AppLogTask.initLog(AppLogTask.kt:71)

**Comment by cnbleu** [comment]
有机型和系统信息吗？麻烦补充一下。或者手动加载一下 sls_producer.so 这个库。

**Comment by HelloFish-2016** [comment]
> 

ndk配置只输出32位so的时候会出现这个问题

**Comment by cnbleu** [comment]
> > 
> 
> ndk配置只输出32位so的时候会出现这个问题

更新到最新版本 2.6.10 再试试

**Comment by syf0113** [comment]
类似报错，更换最新版也没用
 java.lang.UnsatisfiedLinkError: No implementation found for void com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_http_header_inject(long, com.aliyun.sls.android.producer.internal.LogProducerHttpHeaderInjector) (tried Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1http_1header_1inject and Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1http_1header_1inject__JLcom_aliyun_sls_android_producer_internal_LogProducerHttpHeaderInjector_2)
                                                                                         	at com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_http_header_inject(Native Method)
                                                                                         	at com.aliyun.sls.android.producer.LogProducerConfig.setHttpHeaderInjector(LogProducerConfig.java:348)
                                                                                         	at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:79)
                                                                                         	at com.aliyun.sls.android.core.sender.SdkSender.initLogProducer(SdkSender.java:93)
                                                                                         	at com.aliyun.sls.android.core.sender.SdkSender.initialize(SdkSender.java:42)
                                                                                         	at com.aliyun.sls.android.core.SLSAndroid.initializeSdkSender(SLSAndroid.java:186)
                                                                                         	at com.aliyun.sls.android.core.SLSAndroid.initialize(SLSAndroid.java:80)
                                                                                         	at com.tivicloud.utils.APMHelper.init(Unknown Source:65)
                                                                                         	at com.tivicloud.engine.controller.TivicloudController.preInit(Unknown Source:34)
                                                                                         	at com.tivicloud.engine.TivicloudPlatform.onApplicationCreate(Unknown Source:7)
                                                                                         	at com.tivicloud.engine.TivicloudApplication.onCreate(Unknown Source:3)
                                                                                         	at org.cocos2dx.lua.App.onCreate(App.java:14)
                                                                                                ...
