### ISSUE TITLE
初始化时Fatal Exception: java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by henryhong111** [aliyun/aliyun-log-android-sdk#85]
版本： com.aliyun.openservices:aliyun-log-android-sdk:2.6.0

品牌 三星 android版本 12 11 

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxxx.xxx/app_libs/libsls_producer.so" not 
found
       at java.lang.Runtime.load0(Runtime.java:929)
       at java.lang.System.load(System.java:1625)
       at OooOO0o.OooOO0.OooOO0(SoLoader.java:6)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:7)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:4)
       at com.azal.modulepay.OooO00o.OooO00o(AbsBillingManager.java:2)
       at com.hk.azal.live.AzalApplication.OooO0OO(:4)
       at com.hk.azal.live.AzalApplication.initOnMainProcessMainThread(AzalApplication.java:5)
       at com.azal.base.bt.OooO0O0.onCreate(BtApplication.java:11)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
       at android.app.ActivityThread.access$1600(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by cnbleu** [comment]
#83 和这个问题一样

**Comment by cnbleu** [comment]
问题重复，先关闭了

**Comment by henryhong111** [comment]
> 



> 问题重复，先关闭了

这个问题的修复时间有预期吗？
