### ISSUE TITLE
No implementation found for void

### ISSUE THREAD

**Issue by syf0113** [aliyun/aliyun-log-android-sdk#88]
#83 类似报错，更换最新版也没用 
java.lang.UnsatisfiedLinkError:  No implementation found for void com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_http_header_inject(long, com.aliyun.sls.android.producer.internal.LogProducerHttpHeaderInjector) (tried Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1http_1header_1inject and Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1http_1header_1inject__JLcom_aliyun_sls_android_producer_internal_LogProducerHttpHeaderInjector_2)
at com.aliyun.sls.android.producer.LogProducerConfig.log_producer_config_set_http_header_inject(Native Method)
at com.aliyun.sls.android.producer.LogProducerConfig.setHttpHeaderInjector(LogProducerConfig.java:348)
at com.aliyun.sls.android.producer.LogProducerConfig.(LogProducerConfig.java:79)
at com.aliyun.sls.android.core.sender.SdkSender.initLogProducer(SdkSender.java:93)
at com.aliyun.sls.android.core.sender.SdkSender.initialize(SdkSender.java:42)
at com.aliyun.sls.android.core.SLSAndroid.initializeSdkSender(SLSAndroid.java:186)
at com.aliyun.sls.android.core.SLSAndroid.initialize(SLSAndroid.java:80)
at com.tivicloud.utils.APMHelper.init(Unknown Source:65)
at com.tivicloud.engine.controller.TivicloudController.preInit(Unknown Source:34)
at com.tivicloud.engine.TivicloudPlatform.onApplicationCreate(Unknown Source:7)
at com.tivicloud.engine.TivicloudApplication.onCreate(Unknown Source:3)
at org.cocos2dx.lua.App.onCreate(App.java:14)
...

**Comment by syf0113** [comment]
机型 iQOO9   android13
