### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxx.xxx/app_libs/libsls_producer.so"

### ISSUE THREAD

**Issue by henryhong111** [aliyun/aliyun-log-android-sdk#90]
2.6.4
Redmi 9A Android 10 
Galaxy S22+  Android 13
Galaxy Note9 Android 10 

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/xxx.xxx.xxx/app_libs/libsls_producer.so" not found
       at java.lang.Runtime.load0(Runtime.java:938)
       at java.lang.System.load(System.java:1631)
       at com.aliyun.sls.android.producer.utils.SoLoader.loadLibrary(SoLoader.java:55)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:46)
       at com.aliyun.sls.android.producer.LogProducerConfig.<init>(LogProducerConfig.java:40)
       at com.azal.modulepay.AbsBillingManager.initLogProducerClient(AbsBillingManager.java:22)
       at com.azal.main.MainActivity.onCreate(MainActivity.java:233)
       at android.app.Activity.performCreate(Activity.java:7893)
       at android.app.Activity.performCreate(Activity.java:7880)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7563)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by henryhong111** [comment]
@cnbleu 这个问题还是存在啊，有解决方案吗？

**Comment by cnbleu** [comment]
使用[ReLinker](https://github.com/KeepSafe/ReLinker) 手动加载**sls_producer**这个库吧。

**Comment by henryhong111** [comment]
> 

非常感谢
